CREATE TABLE IF NOT EXISTS t_activity (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  customer_id BIGINT UNSIGNED NOT NULL COMMENT '顧客ID',
  contract_id BIGINT UNSIGNED NULL COMMENT '契約ID',
  renewal_case_id BIGINT UNSIGNED NULL COMMENT '満期案件ID',
  accident_case_id BIGINT UNSIGNED NULL COMMENT '事故案件ID',
  sales_case_id BIGINT UNSIGNED NULL COMMENT '営業案件ID',
  activity_date DATE NOT NULL COMMENT '活動日',
  start_time TIME NULL COMMENT '開始時刻',
  end_time TIME NULL COMMENT '終了時刻',
  activity_type VARCHAR(50) NOT NULL COMMENT '活動種別',
  purpose_type VARCHAR(50) NULL COMMENT '用件区分',
  visit_place VARCHAR(200) NULL COMMENT '訪問先',
  interviewee_name VARCHAR(100) NULL COMMENT '面談者',
  subject VARCHAR(200) NULL COMMENT '件名',
  content_summary VARCHAR(500) NOT NULL COMMENT '内容要約',
  detail_text TEXT NULL COMMENT '詳細内容',
  next_action_date DATE NULL COMMENT '次回予定日',
  next_action_note VARCHAR(500) NULL COMMENT '次回アクション',
  result_type VARCHAR(50) NULL COMMENT '結果区分',
  staff_user_id BIGINT UNSIGNED NULL COMMENT '担当者ユーザーID',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '論理削除フラグ',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  PRIMARY KEY (id),
  KEY idx_activity_customer_id (customer_id),
  KEY idx_activity_contract_id (contract_id),
  KEY idx_activity_renewal_case_id (renewal_case_id),
  KEY idx_activity_accident_case_id (accident_case_id),
  KEY idx_activity_sales_case_id (sales_case_id),
  KEY idx_activity_activity_date (activity_date),
  KEY idx_activity_activity_type (activity_type),
  KEY idx_activity_purpose_type (purpose_type),
  KEY idx_activity_next_action_date (next_action_date),
  KEY idx_activity_staff_user_id (staff_user_id),
  KEY idx_activity_customer_date (customer_id, activity_date),
  KEY idx_activity_staff_date (staff_user_id, activity_date),
  KEY idx_activity_deleted_date (is_deleted, activity_date)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='活動履歴';